
Food.create(food_type: "starches")
Food.create(food_type: "vegetables")
Food.create(food_type: "roasted vegetables")
Food.create(food_type: "soft cheese")
Food.create(food_type: "hard cheese")
Food.create(food_type: "fish")
Food.create(food_type: "rich fish")
Food.create(food_type: "white meat")
Food.create(food_type: "red meat")
Food.create(food_type: "cured meats")
Food.create(food_type: "sweets")
